### PR TITLE
Code changes needed for initial release

### PR DESCRIPTION
**Pull request by yuvaldeg**

### CODE REVIEW

**Comment by patrickstuedi** [comment]
Regarding the support for empty sgl, shouldn't we make a similar change to the postSend side too?

**Comment by patrickstuedi** [comment]
Regarding the support to register raw addresses. That opens the door to unchecked RDMA operations consisting of arbitrary memory, possible owned by the garbage collector. Can you describe your use case briefly?

**Comment by yuvaldeg** [comment]
Thanks for reviewing, Patrick

Re "Regarding the support for empty sgl, shouldn't we make a similar change to the postSend side too?"
I agree, it is a valid use case for postSend(), we just didn't have the need for it. we can add it later.

Re "Regarding the support to register raw addresses. That opens the door to unchecked RDMA operations consisting of arbitrary memory, possible owned by the garbage collector. Can you describe your use case briefly?"
The reason we had to introduce this change, is that so we can register addresses for mmap() files, which are intentionally not wrapped in ByteBuffers to reduce overhead.
Please note that this change doesn't expose any new vulnerability - the ability to register non-GC'ed addresses is still there. E.g. user calls regMr with a proper ByteBuffer. regMr doesn't hold a ref to that ByteBuffer, and so if all refs are eliminated from that ByteBuffer, then at any minute the GC might release it.
That will result in seg fault or access violation.
In my opinion this is ok, whatever we decide to do, still this sort of issues can occur. Even if we take a ref on the ByteBuffer in regMr, then the user can cheat and provide a ByteBuffer with a wrong address that is set using reflection. Since this is a low-level library, I suppose it is ok to expose such vulnerabilities for the sake of performance.

**Comment by patrickstuedi** [comment]
Thanks for the comments:

Re "I agree, it is a valid use case for postSend(), we just didn't have the need for it. we can add it later."
Would prefer to add this to the send side rather sooner than later to keep things in sync. If you have time to add it that'd be great, otherwise let me know and I can also do it.

Re "addresses for mmap() .." We also pretty much work only with mmaped buffers in anything we implement on top of DiSNI because we want control over the page size (huge pages). We use MappedByteBuffer for this, which is extends ByteBuffer, that was no option for you?

**Comment by patrickstuedi** [comment]
Re "Since this is a low-level library, I suppose it is ok to expose such vulnerabilities "
Agree. On the other if we can avoid vulnerabilities without functionality loss that'd be even better. I'm wondering if it would make sense to keep a reference for every registered Buffer in DiSNI and then delete the ref again when unregistering. Wouldn't that solve the GC/seg fault issue?

**Comment by yuvaldeg** [comment]
Re postSend() - I agree that for completeness we should add that too, but that has to be tested first before suggesting the change, and that requires quite amount of work

Re MappedByteBuffer - we found that mapping the file with a raw pointer, rather than through MappedByteBuffer gives a slight performance improvement due to less overhead in GC, etc. In particular - it takes ages for GC to get the file unmapped once all refs are gone

**Comment by patrickstuedi** [comment]
Re MappedByteBuffer - Ok, I see. Here is what I suggest. We can add the the raw virtual address regMr feature to the DiSNI verbs level API, that is RdmaVerbs, IbvPd (with the corresponding Nat classes), but I'd prefer not to add this to the DiSNI RDMA Endpoint API (e.g., RdmaEndpoint). Going forward if we can maintain the philosophy where the raw DiSNI verbs API can have all sorts of performance features -- and possibly expose vulnerabilities -- but we keep the Endpoint API strict, then that's something that will work for me. Assuming you guys are not using the Endpoint API anyway, that might be ok I hope. What do you think?

**Comment by yuvaldeg** [comment]
Yes, I agree with this approach.

**Pull request merged**
