### PR TITLE
Added libdisni RPM/DEB build environment

### PR DESCRIPTION
**Pull request by vladsokolovsky**

### CODE REVIEW

**Comment by yuvaldeg** [comment]
Hi Patrick,
These are the necessary changes for integrating with MLNX_OFED: ability to build RPM/DEB files

I already noticed that version 1.1 is hardcoded here, and Vlad will take care of it soon

Please share your comments if you have any

Cheers,
Yuval

**Comment by patrickstuedi** [comment]
Vlad, Yuval, 

Great, the ability to build RPM/DEB is generally very helpful, thanks a lot! Should be an easy merge..

-Patrick

**Comment by patrickstuedi** [comment]
I notice that this is partially undoing some of the changes @patrickmacarthur did in his recent pull request: 

https://github.com/zrlio/disni/commit/a1948b8bd8c7199e05a53ab2468c20de669ae946. 

For instance one argument there was since we don't need a static library for JNI anyway, there is also no need to built a libtool library, etc, which I thought made sense. Now we are again adding +libtoolize --force --copy. 

Also we are adding +autoconf, is that need given we do autoreconf?

My knowledge about GNU autotools was just sufficient to get the basic setup ready initially but I'm not an expert here. Can we discuss this quickly.

**Comment by patrickmacarthur** [comment]
Chiming in:

* autoreconf is a wrapper that automatically calls autoconf, automake, autoheader, libtoolize, etc. in the correct order. @vladsokolovsky I'm curious why you believe that it is not sufficient in this case.
* I think libtool is still required to (easily) build a shared library with autotools; my changes just made it so it doesn't build a static library by default anymore. Using autoreconf means that we don't need to care in the autoprepare.sh script.
* Looking at the entire PR, I don't think installing the header files is useful as the only thing that uses the library is JNI itself (unless there really is something else (ab)using the JNI library).
* The Ubuntu convention for JNI libraries seems to be to call them "lib<LIBRARY>-java-jni", place the library in `/usr/lib/$(DEB_HOST_MULTIARCH)/jni`, and not create a -dev package. I presume it's the same or similar in Debian.

**Comment by vladsokolovsky** [comment]
Hi Patrick,
I addressed your comments and pushed my changes.
Can you please review/merge?

Thanks,
Vladimir

**Comment by patrickmacarthur** [comment]
Looks good to me

**Comment by patrickstuedi** [comment]
Thanks Vlad, Yuval!

**Pull request merged**
